### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by qwe852147** [lisps/plugin-sneakyindexfix#1]
Dear author，
 I try to use this plugin but it does not work.
The result is similar to use sneaky_index  .

The plugin is work now?

**Comment by lisps** [comment]
for me it works. what exactly does not work.

have you followed the following instructions https://www.dokuwiki.org/plugin:sneakyindexfix ?

**Comment by qwe852147** [comment]
Thanks，it my falut.It Work in sitemap.
I have another question that it can work for indexmenu plugin?

This is indexmenu plugin .
https://www.dokuwiki.org/plugin:indexmenu
It similar sitemap.

**Comment by lisps** [comment]
i don't know the indexmenu plugin well enough. If it is checking the pagerights then it should work out of the box.

**Comment by qwe852147** [comment]
Thanks,I'll try it again.
